context("hard_tree")

test_that("usage", {

  # Thanks to Fien Strijthaegen for providing a testing tree

  focal_tree <- ape::read.tree(text = "(151:34,(152:2,((((153:10,154:16):1,155:24):2,156:2):6,(157:5,((158:0,(((159:0,160:5):14,161:1):0,((((162:4,163:0):6,164:0):0,(165:22,166:4):3):1,167:13):4):9):3,(168:25,169:3):29):2):0):2):0,170:11,171:4):0;") #nolint
  all_stats <- treestats::calc_all_stats(focal_tree)

  testthat::expect_true(is.na(all_stats$gamma))
  testthat::expect_true(is.na(all_stats$sackin))
  testthat::expect_true(is.na(all_stats$colless))
  testthat::expect_true(is.na(all_stats$beta))
  testthat::expect_true(is.na(all_stats$blum))
  testthat::expect_true(is.na(all_stats$avg_ladder))
  testthat::expect_true(is.na(all_stats$max_ladder))
  testthat::expect_true(is.na(all_stats$cherries))
  testthat::expect_true(is.na(all_stats$stairs))
  testthat::expect_true(is.na(all_stats$j_one))
  testthat::expect_true(is.na(all_stats$b1))
  testthat::expect_true(is.na(all_stats$b2))
  testthat::expect_true(is.na(all_stats$area_per_pair))
  testthat::expect_true(is.na(all_stats$average_leaf_depth))
  testthat::expect_true(is.na(all_stats$i_stat))
  testthat::expect_true(is.na(all_stats$ew_colless))
  testthat::expect_true(is.na(all_stats$rogers))
  testthat::expect_true(is.na(all_stats$stairs2))
  testthat::expect_true(is.na(all_stats$tot_coph))
  testthat::expect_true(is.na(all_stats$symmetry_nodes))
  testthat::expect_true(is.na(all_stats$rquartet))
  testthat::expect_true(is.na(all_stats$wiener))
  testthat::expect_true(is.na(all_stats$max_betweenness))
  testthat::expect_true(is.na(all_stats$max_closeness))
  testthat::expect_true(is.na(all_stats$max_closenessW))
  testthat::expect_true(is.na(all_stats$diameter))
  testthat::expect_true(is.na(all_stats$eigen_centrality))
  testthat::expect_true(is.na(all_stats$eigen_centralityW))

  testthat::expect_true(is.na(all_stats$min_laplace))
  testthat::expect_true(is.na(all_stats$max_laplace))
  testthat::expect_true(is.na(all_stats$min_adj))
  testthat::expect_true(is.na(all_stats$max_adj))

  brts_stats <- treestats::calc_brts_stats(focal_tree)
  testthat::expect_true(is.na(brts_stats$gamma))

  bal_stats <- treestats::calc_balance_stats(focal_tree)
  testthat::expect_true(is.na(bal_stats$sackin))
  testthat::expect_true(is.na(bal_stats$colless))
  testthat::expect_true(is.na(bal_stats$beta))
  testthat::expect_true(is.na(bal_stats$blum))
  testthat::expect_true(is.na(bal_stats$avg_ladder))
  testthat::expect_true(is.na(bal_stats$max_ladder))
  testthat::expect_true(is.na(bal_stats$cherries))
  testthat::expect_true(is.na(bal_stats$stairs))
  testthat::expect_true(is.na(bal_stats$j_one))
  testthat::expect_true(is.na(bal_stats$b1))
  testthat::expect_true(is.na(bal_stats$b2))
  testthat::expect_true(is.na(bal_stats$area_per_pair))
  testthat::expect_true(is.na(bal_stats$average_leaf_depth))
  testthat::expect_true(is.na(bal_stats$i_stat))
  testthat::expect_true(is.na(bal_stats$ew_colless))
  testthat::expect_true(is.na(bal_stats$rogers))
  testthat::expect_true(is.na(bal_stats$stairs2))
  testthat::expect_true(is.na(bal_stats$tot_coph))
  testthat::expect_true(is.na(bal_stats$symmetry_nodes))
  testthat::expect_true(is.na(bal_stats$rquartet))
  testthat::expect_true(is.na(bal_stats$diameter))

  # test phylo_to_l and rebase_ltable on polytomies:
  testthat::expect_silent(
    ltab  <- treestats::phylo_to_l(focal_tree))
  testthat::expect_silent(
    ltab2 <- treestats::rebase_ltable(ltab)
  )
})
